#!/usr/bin/with-contenv bash

until [ -e "/config/rtorrent/rtorrent_sess/rtorrent.lock" ];
do
    sleep 1s
done

rtorrent_pid=$(< /config/rtorrent/rtorrent_sess/rtorrent.lock cut -d '+' -f 2)
tail -n 1 -f /config/log/rtorrent/rtorrent.log
