#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*               linuxserver/rutorrent                *
*                                                    *
*   https://hub.docker.com/r/linuxserver/rutorrent   *
*                                                    *
*   https://github.com/linuxserver/docker-rutorrent  *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
